POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhbXVlbCIsImlkIjoiNmE3MzNhNzYyMmQzMzk3MzUzNDJlZDk5IiwiaWF0IjoxNzg1OTM3NTI0fQ.tmRsHSD_y91MIZddJyLmO4_U_8OQ5DLpMzIF7GE2Yzs

{
    "content": "dkdkdkdkdkdk",
    "important": true
}